# Generated by Django 2.0.7 on 2019-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='rank',
            field=models.CharField(choices=[('OW', 'Owner'), ('MN', 'Manager'), ('WK', 'Worker')], default='WK', max_length=2),
        ),
    ]
