# Generated by Django 2.2.1 on 2019-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='numberPrefix',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='rank',
            field=models.CharField(choices=[('OW', 'Owner'), ('MN', 'Manager'), ('WK', 'Worker')], default='WK', max_length=2),
        ),
    ]
