# Generated by Django 2.1.3 on 2019-05-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190511_1339'),
        ('projects', '0002_auto_20190511_1332'),
    ]

    operations = [
    ]
