# Generated by Django 2.0.7 on 2019-05-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190511_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Graph'),
        ),
    ]
