# Generated by Django 2.1.3 on 2019-05-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190511_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='graph',
        ),
        migrations.AddField(
            model_name='graph',
            name='graph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
