# Generated by Django 2.1.3 on 2019-05-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190512_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='graph',
            new_name='project',
        ),
    ]
