# Generated by Django 2.1.3 on 2019-05-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190512_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required', to='projects.Task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need', to='projects.Task')),
            ],
        ),
    ]
