# Generated by Django 2.1.3 on 2019-05-12 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_requiredtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_tasks',
            field=models.ManyToManyField(related_name='required', through='projects.RequiredTask', to='projects.Task'),
        ),
        migrations.AlterField(
            model_name='requiredtask',
            name='required_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed', to='projects.Task'),
        ),
    ]
