# Generated by Django 2.1.3 on 2019-05-12 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190512_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='required_tasks',
        ),
        migrations.AlterField(
            model_name='requiredtask',
            name='required_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required', to='projects.Task'),
        ),
    ]
