# Generated by Django 2.1.3 on 2019-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190512_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='file',
            field=models.ImageField(upload_to='graphs/'),
        ),
    ]
